In [1]:
import numpy as np
import matplotlib.pyplot as plt

Let z be m x n matrix, with row vectors of dimension n. let c be an n-dim vector. and A an nxn matrix. Define $k:=n(n+1)/2$, and let x be vector with $(a_{11}, a_{12}, ..., a_{1n}, a_{22}, a_{23}, ..., a_{nn}) = (x_1, x_2, ..., x_k)$, and $(c_1, c_2, ..., c_n) = (x_{k+1}, x_{k+2}, ..., x_{k + n})$

## Model 1

In [159]:
def r_plus(A, c, z):
    v = z - c    
    x = (v @ A * v).sum(axis=1)
    return np.maximum(x - 1, 0)

def r_minus(A, c, z):
    v  = z - c    
    x = (v @ A * v).sum(axis=1)
    return np.maximum(1 - x, 0)

def r(A, c, z, w):
    x_plus = r_plus(A, c, z)
    x_minus = r_minus(A, c, z)
    return (w == 1) * x_plus + (w == -1) * x_minus

def f(A, c, z, w):
    R = r(A, c, z, w)
    return np.sum(R**2)

def update_A(A, x):
    n = A.shape[0]
    a = x[:n*(n+1)//2]
    for j in range(n):
        A[j, j:] = x[j*n:(j+1)*n-j]
    return A
        
def update_c(c, x):
    c = x[-n:]
    return c

def extract_a(A):
    n = A.shape[0]
    k = n*(n+1)//2
    a = np.zeros(k)
    for j in range(n):
        a[j*n:(j+1)*n-j] = A[j, j:]
    return a

In [160]:
def grad_f(A, c, z, w):
    v = z - c 

In [161]:
A

array([[1, 4],
       [3, 2]])

In [162]:
v

array([[-1. ,  1. ],
       [ 2. ,  2. ],
       [ 0. , -2. ],
       [-0.5,  0. ]])

In [179]:
(v * (v* np.ones_like(A)).T)[0]

ValueError: operands could not be broadcast together with shapes (4,2) (2,2) 

In [183]:
a = x[:n*(n+1)//2]
for j in range(n):
    A[j, j:] = x[j*n:(j+1)*n-j]

ValueError: could not broadcast input array from shape (3) into shape (2)

In [184]:
q * (q * np.ones_like(A)).T
for i in range(v.shape[0]):
    print(i)
    print((v[i] * ( v[i] * np.ones_like(A)).T)[:,:,])

0
[[ 1. -1.]
 [-1.  1.]]
1
[[ 4.  4.]
 [ 4.  4.]]
2
[[ 0. -0.]
 [-0.  4.]]
3
[[ 0.25 -0.  ]
 [-0.    0.  ]]


In [185]:
np.zeros((n, *A.shape))

array([[[ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.]]])

In [165]:
def ri_delA(dri):
    r = np.zeros(k + n)
    for i in range(n):
        dri[]
        

SyntaxError: unexpected EOF while parsing (<ipython-input-165-64c7d1d638f5>, line 4)

In [209]:
# Partial derivative og r_i

def del_r(A, c, z):
    n = c.size
    k = n * (n+1)//2
    dR = np.zeros((m, k + n))
    for i in range(m):
        dR[i,:k] = r_delA(A, c, z[i])
        dr[i,k:] = r_delC(A, c, z[i])
        
def r_delA(A, c, z):
    n = c.size
    v = z - c
    dr = np.zeros(m)
    for i in range(n):
        dr
        

# returns a vector of length m with the i-th coeficcient for residual r_j.
def r_delc(A, c, z):
    v = z - c
    return -2 * (v @ A).sum(axis=1)

r_delc(A, c, z)

array([ -0., -40.,  20.,   5.])

## Model 2

In [116]:
def r_plus(A, b, z):    
    x = (z @ A * z).sum(axis=1) + z @ b
    return np.maximum(x - 1, 0)

def r_minus(A, b, z):
    x = (z @ A * z).sum(axis=1) + z @ b
    return np.maximum(1 - x, 0)

def r(A, c, z, w):
    x_plus = r_plus(A, c, z)
    x_minus = r_minus(A, c, z)
    return (w == 1) * x_plus + (w == -1) * x_minus

def f(A, c, z, w):
    R = r(A, c, z, w)
    return np.sum(R**2)

def update_A(A, x):
    n = A.shape[0]
    a = x[:n*(n+1)//2]
    for j in range(n):
        A[j, j:] = x[j*n:(j+1)*n-j]
    return A
        
def update_c(c, x):
    c = x[-n:]
    return c

### DRAFT & TESTING 

In [206]:
A = np.array((1, 4, 3, 2)).reshape(2,2)
c = np.array((2, 1))
b = c - 1
z = np.array((1, 2, 4, 3, 2, -1, 1.5, 1)).reshape(4, 2)
w = np.array((1, 1, 1, -1))

In [187]:
c

array([2, 1])

In [188]:
b

array([1, 0])

In [189]:
z

array([[ 1. ,  2. ],
       [ 4. ,  3. ],
       [ 2. , -1. ],
       [ 1.5,  1. ]])

In [190]:
v  = z - c

In [191]:
c.T @ A @ c

20

In [192]:
(v @ A * v).sum(axis=1)

array([ -4.  ,  40.  ,   8.  ,   0.25])

In [193]:
(z @ A * z).sum(axis=1)

array([  23.  ,  118.  ,   -8.  ,   14.75])

In [194]:
z @ b

array([ 1. ,  4. ,  2. ,  1.5])

In [195]:
r_plus(A, c, z)

array([  0.,  39.,   7.,   0.])

In [196]:
r_minus(A, c, z)

array([ 5.  ,  0.  ,  0.  ,  0.75])

In [197]:
r(A, c, z, w)

array([  0.  ,  39.  ,   7.  ,   0.75])

In [198]:
f(A, c, z, w)

1570.5625

In [199]:
A = np.zeros((3, 3))
x = np.array((1, 2, 3, 4, 5, 6, 7, 8, 9))
n = 3
a = x[:n*(n+1)//2]
c = x[-n:]

In [200]:
a

array([1, 2, 3, 4, 5, 6])

In [201]:
c

array([7, 8, 9])

In [208]:
def extract_a(A):
    n = A.shape[0]
    k = n*(n+1)//2
    a = np.zeros(k)
    for j in range(n):
        a[j*n:(j+1)*n-j] = A[j, j:]
    return a

extract_a(A)

array([ 1.,  4.,  2.])

In [207]:
A

array([[1, 4],
       [3, 2]])