In [54]:
import numpy as np
import matplotlib.pyplot as plt

Let z be m x n matrix, with row vectors of dimension n. let c be an n-dim vector. and A an nxn matrix. Define $k:=n(n+1)/2$, and let x be vector with $(a_{11}, a_{12}, ..., a_{1n}, a_{22}, a_{23}, ..., a_{nn}) = (x_1, x_2, ..., x_k)$, and $(c_1, c_2, ..., c_n) = (x_{k+1}, x_{k+2}, ..., x_{k + n})$

## Model 1

In [55]:
def r_plus(A, c, z):
    v = z - c    
    x = (v @ A * v).sum(axis=1)
    return np.maximum(x - 1, 0)

def r_minus(A, c, z):
    v  = z - c    
    x = (v @ A * v).sum(axis=1)
    return np.maximum(1 - x, 0)

def r(A, c, z, w):
    x_plus = r_plus(A, c, z)
    x_minus = r_minus(A, c, z)
    return (w == 1) * x_plus + (w == -1) * x_minus

def f(A, c, z, w):
    R = r(A, c, z, w)
    return np.sum(R**2)

def update_A(A, x):
    n = A.shape[0]
    a = x[:n*(n+1)//2]
    for j in range(n):
        A[j, j:] = x[j*n:(j+1)*n-j]
    return A
        
def update_c(c, x):
    c = x[-n:]
    return c

## Model 2

In [53]:
def r_plus(A, b, z):    
    x = (z @ A * z).sum(axis=1) + z @ b
    return np.maximum(x - 1, 0)

def r_minus(A, b, z):
    x = (z @ A * z).sum(axis=1) + z @ b
    return np.maximum(1 - x, 0)

def r(A, c, z, w):
    x_plus = r_plus(A, c, z)
    x_minus = r_minus(A, c, z)
    return (w == 1) * x_plus + (w == -1) * x_minus

def f(A, c, z, w):
    R = r(A, c, z, w)
    return np.sum(R**2)

def update_A(A, x):
    n = A.shape[0]
    a = x[:n*(n+1)//2]
    for j in range(n):
        A[j, j:] = x[j*n:(j+1)*n-j]
    return A
        
def update_c(c, x):
    c = x[-n:]
    return c

### DRAFT & TESTING 

In [37]:
A = np.array((1, 0, 0, 1)).reshape(2,2)
c = np.array((2, 1))
b = c -1
z = np.array((1, 2, 4, 3, 2, -1, 1.5, 1)).reshape(4, 2)
w = np.array((1, 1, 1, -1))

In [38]:
c

array([2, 1])

In [39]:
b

array([1, 0])

In [40]:
z

array([[ 1. ,  2. ],
       [ 4. ,  3. ],
       [ 2. , -1. ],
       [ 1.5,  1. ]])

In [41]:
v  = z - c

In [42]:
c.T @ A @ c

5

In [43]:
(v @ A * v).sum(axis=1)

array([ 2.  ,  8.  ,  4.  ,  0.25])

In [44]:
(z @ A * z).sum(axis=1)

array([  5.  ,  25.  ,   5.  ,   3.25])

In [45]:
z @ b

array([ 1. ,  4. ,  2. ,  1.5])

In [46]:
r_plus(A, c, z)

array([ 1.,  7.,  3.,  0.])

In [47]:
r_minus(A, c, z)

array([ 0.  ,  0.  ,  0.  ,  0.75])

In [48]:
r(A, c, z, w)

array([ 1.  ,  7.  ,  3.  ,  0.75])

In [49]:
f(A, c, z, w)

59.5625

In [50]:
A = np.zeros((3, 3))
x = np.array((1, 2, 3, 4, 5, 6, 7, 8, 9))
n = 3
a = x[:n*(n+1)//2]
c = x[-n:]

In [56]:
a

array([1, 2, 3, 4, 5, 6])

In [57]:
c

array([7, 8, 9])